### PR TITLE
Fix changing connection name

### PR DESCRIPTION
**Pull request by dustinsmith1024**
I wasn't able to actually change connections. I had to expose the name in the commander args to get it pass through.

Also the first attempt to connect swallowed errors for me on development. So it'd be nice to log it out somehow. I am not sure we want to use console.error but it was the easiest thing for me right now.

### CODE REVIEW

**Comment by jeanfortheweb** [comment]
This seems like a connection name is then required? By swallowed you mean --connection someConnection still used "default" ?

**Comment by dustinsmith1024** [comment]
So if I passed a connection name it was just setting it to `true`. That was because there was no pattern set in the command line option. It is not required now as the default is setup here: https://github.com/jeanfortheweb/typeorm-fixture-builder/pull/9/files#diff-cd02b9e0b731a6a1dedefed142f4419bR23.

To reproduce you can just add a second option to your `ormconifg.json` file and try to use the non default one.

**Comment by jeanfortheweb** [comment]
I see. But I think I don't like the idea to fall back to default when this was not the users intention when he passed a custom connection name. So the try/catch as before should spit out a meaningful error without changes?

**Comment by jeanfortheweb** [comment]
Hello @dustinsmith1024,
I just released 2.0, where things have changed quite a bit. It would be nice if you take a look. 
I included your fix partially. If there are still issues, I would be thankful if you open a new issue for this. Also, there is now some end to end testing for the CLI where we could create a test case if necessary.

**Pull request closed without merging**
